name: Auto Preprocessing Data

on:
  push:
    branches:
      - main
      - master

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Check Files
      run: |
        pwd
        ls
        ls preprocessing

    - name: Run preprocessing
      run: |
        cd preprocessing
        python automate_Nabila-Choirunisa.py

    - name: Upload Cleaned Dataset
      uses: actions/upload-artifact@v4
      with:
        name: cleaned-dataset
        path: preprocessing/Churn_Modelling_clean.csv